<?php
/**
 * DEFINE ID OF ALL TEMPLATE'S ELEMENTS
 *
 * Created by Huy Ngo.
 * User: nqhuy
 * Date: 4/6/2018
 * Time: 10:45 AM
 */
  const PAGE_DEFAULT_BACKGROUND_ID = 106;

  const CONTACT_PAGE_ID = 14;
  const ABOUT_PAGE_ID = 10;
  const PRODUCT_PAGE_ID = 2;

  const HOMEINTRO_POST_ID = 1;
  const HOME_POST_ID = 51;
  const VESTIBULUM_POST_ID = 21;
  const DONEC_POST_ID = 23;
  const HABITASSE_POST_ID = 25;
  const HAVEQUESTION_POST_ID = 34;
  const FACILISSIS_POST_ID = 36;
  const FOOTER_POST_ID = 102;
  const COPYRIGHT_POST_ID = 96;
  const SOCIAL_POST_ID = 104;
  const CONTACT_DETAIL_POST_ID = 122;
  const CONTACT_FORM_POST_ID = 111;
  const CONTACT_MAP_POST_ID = 109;

  const PLATFORM_CATEGORY_ID = 9;
  const SOLUTION_CATEGORY_ID = 10;
  const PRODUCT_CATEGORY_ID = 11;

  const MAX_SITEMAP_NUMBER = 2;

  const ABOUT_US_PAGE_BTN = 'Meet UNITY today';
  const VIDEO_BTN_NAME = 'WATCH INTRO VIDEO';
  const ENQUIRE_BTN_NAME = 'ENQUIRE NOW';
